# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 迭代.py
# Created on: 2024-05-07 11:14:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
qiu = "D:\\qiu"
Name = "TEMP_2020"
TEMP_1950_shp = "D:\\qiu\\TEMP_2020.shp"
Output_variance_of_prediction_raster = ""
n_name_ = "D:\\qiu\\n%name%"
省_shp = "C:\\Users\\hqm\\Desktop\\2021年全国行政区划+1940-2020年全球范围气象站点的逐日平均气温数据\\2021年全国行政区划\\省.shp"
m_name_ = "D:\\qiu\\m%name%"

# Process: Iterate Feature Classes
arcpy.IterateFeatureClasses_mb(qiu, "", "POINT", "NOT_RECURSIVE")

# Process: Kriging
arcpy.gp.Kriging_sa(TEMP_1950_shp, "TEMP", n_name_, "Spherical 0.614200", "0.05", "VARIABLE 12", Output_variance_of_prediction_raster)

# Process: Extract by Mask
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = ""
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = "73.5023550000001 3.8370300000001 135.09567 53.563624"
arcpy.gp.ExtractByMask_sa(n_name_, 省_shp, m_name_)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1

